using System.Globalization;
using System.Text;
using Liquidcast.Api.Models;

namespace Liquidcast.Api.Services;

/// <summary>
/// Renders the persistent Liquidsoap script from the current settings. The
/// script is generated once at boot; content changes happen at runtime over the
/// control socket, never by regenerating + restarting.
/// </summary>
public class ScriptGenerator
{
    private readonly RuntimeConfig _cfg;

    public ScriptGenerator(RuntimeConfig cfg) => _cfg = cfg;

    private static string F(double d) => d.ToString("0.0##", CultureInfo.InvariantCulture);
    // Escapes \r/\n as well as \/" — the annotate URI this builds is sent as a single
    // line over the control socket (LiquidsoapClient writes cmd + "\n"); a raw newline
    // in a value (e.g. from an uploaded file's ID3 tags) would otherwise split into an
    // extra line and let untrusted metadata inject further control-socket commands.
    private static string Q(string s) => "\"" + s
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"")
        .Replace("\r", "\\r")
        .Replace("\n", "\\n")
        + "\"";
    private static string LiqPath(string p) => Q(p.Replace('\\', '/'));

    public string Generate()
    {
        var s = _cfg.Settings;
        var sb = new StringBuilder();

        sb.AppendLine("# Generated by Liquidcast — do not edit by hand.");
        sb.AppendLine("# This process stays up for its whole lifetime; content is pushed over the control socket.");
        sb.AppendLine();
        sb.AppendLine("settings.log.file.set(true)");
        sb.AppendLine($"settings.log.file.path.set({LiqPath(_cfg.LogPath)})");
        // Also emit to stdout so the .NET host captures Liquidsoap logs live (the file is
        // buffered and may not flush while the process keeps running).
        sb.AppendLine("settings.log.stdout.set(true)");
        sb.AppendLine($"settings.log.level.set({s.LiquidsoapLogLevel})");
        sb.AppendLine("settings.init.allow_root.set(true)");
        sb.AppendLine();

        // --- control interface ---
        if (s.EffectiveControlMode == ControlMode.UnixSocket)
        {
            sb.AppendLine("settings.server.socket.set(true)");
            sb.AppendLine($"settings.server.socket.path.set({LiqPath(_cfg.SocketPath)})");
            sb.AppendLine("settings.server.socket.permissions.set(0o600)");
        }
        else
        {
            sb.AppendLine("settings.server.telnet.set(true)");
            sb.AppendLine("settings.server.telnet.bind_addr.set(\"127.0.0.1\")");
            sb.AppendLine($"settings.server.telnet.port.set({s.TelnetPort})");
        }
        sb.AppendLine();

        // --- main just-in-time queue: backend pushes tracks via "main.push <annotate-uri>" ---
        sb.AppendLine("main = request.queue(id=\"main\")");
        sb.AppendLine();

        // --- crossfade (per-track overridable via liq_cross_duration / liq_fade_* metadata) ---
        sb.AppendLine($"mixed = crossfade(duration={F(s.DefaultCrossfadeSec)}, fade_in={F(s.FadeInSec)}, fade_out={F(s.FadeOutSec)}, main)");
        sb.AppendLine();

        // --- fallback chain: guarantees the mount never goes silent / disconnects ---
        var branches = new List<string> { "mixed" };
        if (s.FallbackMode == FallbackMode.Playlist)
        {
            sb.AppendLine($"fallback_pl = playlist(id=\"fallback\", mode=\"randomize\", reload_mode=\"watch\", {LiqPath(_cfg.FallbackDir)})");
            branches.Add("fallback_pl");
        }
        branches.Add("blank(id=\"silence\")"); // default duration = infinite silence
        sb.AppendLine($"radio = fallback(track_sensitive=false, [{string.Join(", ", branches)}])");
        sb.AppendLine();

        // --- expose current on-air metadata over the control socket as "meta.now" ---
        sb.AppendLine("current_meta = ref(\"\")");
        sb.AppendLine("radio.on_metadata(synchronous=true, fun (m) -> begin");
        sb.AppendLine("  artist = m[\"artist\"]");
        sb.AppendLine("  title = m[\"title\"]");
        sb.AppendLine("  current_meta := if title == \"\" then \"\" else (if artist == \"\" then title else artist ^ \" - \" ^ title end) end");
        sb.AppendLine("end)");
        sb.AppendLine("server.register(namespace=\"meta\", description=\"Current on-air track\", \"now\", fun (_) -> current_meta())");
        sb.AppendLine();

        // --- persistent Icecast output ---
        sb.AppendLine("output.icecast(");
        // Encode MP3 via ffmpeg/libmp3lame — the builtin %mp3 encoder is absent from some
        // Liquidsoap builds (e.g. the Windows portable build), but ffmpeg is present on both
        // that build and the Linux savonet image.
        sb.AppendLine($"  %ffmpeg(format=\"mp3\", %audio(codec=\"libmp3lame\", b=\"{s.Bitrate}k\")),");
        sb.AppendLine($"  host={Q(s.IcecastHost)}, port={s.IcecastPort}, password={Q(s.IcecastPassword)},");
        sb.AppendLine($"  mount={Q(s.IcecastMount)}, name={Q(s.StreamName)}, description={Q(s.StreamDescription)},");
        sb.AppendLine($"  genre={Q(s.Genre)},");
        sb.AppendLine("  fallible=false,");
        sb.AppendLine("  radio)");

        return sb.ToString();
    }

    /// <summary>Builds an annotate: URI carrying metadata, cue points and crossfade overrides.</summary>
    public static string BuildRequestUri(string filePath, string? title, string? artist,
        double? cueIn, double? cueOut, double? crossfadeSec)
    {
        var ann = new List<string>();
        void Add(string k, string? v)
        {
            if (string.IsNullOrEmpty(v)) return;
            ann.Add($"{k}={Q(v)}");
        }
        Add("title", title);
        Add("artist", artist);
        if (cueIn is > 0) ann.Add($"liq_cue_in={F(cueIn.Value)}");
        if (cueOut is > 0) ann.Add($"liq_cue_out={F(cueOut.Value)}");
        if (crossfadeSec is >= 0) ann.Add($"liq_cross_duration={F(crossfadeSec.Value)}");

        // Not a quoted string literal (it's the trailing URI), so strip rather than
        // escape — a raw \r/\n here would break the single-line control-socket command.
        var path = filePath.Replace('\\', '/').Replace("\r", "").Replace("\n", "");
        return ann.Count == 0 ? path : $"annotate:{string.Join(",", ann)}:{path}";
    }
}
