// <auto-generated />
using System;
using Liquidcast.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Liquidcast.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260704110758_AddAdminUserTokenVersion")]
    partial class AddAdminUserTokenVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Liquidcast.Api.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("Liquidcast.Api.Models.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bitrate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ControlMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("DefaultCrossfadeSec")
                        .HasColumnType("REAL");

                    b.Property<double>("FadeInSec")
                        .HasColumnType("REAL");

                    b.Property<double>("FadeOutSec")
                        .HasColumnType("REAL");

                    b.Property<int>("FallbackMode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FallbackPlaylistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IcecastAdminPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IcecastAdminUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IcecastHost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IcecastMount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IcecastPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IcecastPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LiquidsoapLogLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LiquidsoapPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("StreamDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TelnetPort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bitrate = 128,
                            ControlMode = 1,
                            DataPath = "data",
                            DefaultCrossfadeSec = 3.0,
                            FadeInSec = 2.0,
                            FadeOutSec = 3.0,
                            FallbackMode = 0,
                            IcecastAdminPassword = "hackme",
                            IcecastAdminUser = "admin",
                            IcecastHost = "localhost",
                            IcecastMount = "/stream",
                            IcecastPassword = "hackme",
                            IcecastPort = 8000,
                            LiquidsoapLogLevel = 3,
                            StreamDescription = "Powered by Liquidcast",
                            StreamName = "Liquidcast",
                            TelnetPort = 1234
                        });
                });

            modelBuilder.Entity("Liquidcast.Api.Models.BackupSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeepCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastBackupAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduleTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetPath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BackupSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Enabled = false,
                            KeepCount = 10,
                            ScheduleTime = "02:00"
                        });
                });

            modelBuilder.Entity("Liquidcast.Api.Models.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CrossfadeOverrideSec")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Liquidcast.Api.Models.PlaylistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CrossfadeSec")
                        .HasColumnType("REAL");

                    b.Property<double?>("CueInSec")
                        .HasColumnType("REAL");

                    b.Property<double?>("CueOutSec")
                        .HasColumnType("REAL");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("TrackId");

                    b.ToTable("PlaylistItems");
                });

            modelBuilder.Entity("Liquidcast.Api.Models.ScheduleSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HardCut")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Loop")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Recurrence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.ToTable("ScheduleSlots");
                });

            modelBuilder.Entity("Liquidcast.Api.Models.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Album")
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT");

                    b.Property<int>("Bitrate")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DurationSec")
                        .HasColumnType("REAL");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("Liquidcast.Api.Models.PlaylistItem", b =>
                {
                    b.HasOne("Liquidcast.Api.Models.Playlist", "Playlist")
                        .WithMany("Items")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Liquidcast.Api.Models.Track", "Track")
                        .WithMany("PlaylistItems")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Liquidcast.Api.Models.ScheduleSlot", b =>
                {
                    b.HasOne("Liquidcast.Api.Models.Playlist", "Playlist")
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("Liquidcast.Api.Models.Playlist", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Liquidcast.Api.Models.Track", b =>
                {
                    b.Navigation("PlaylistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
